<?php

/**
 * RBAC fallback (jika tabel roles/permissions belum di-seed).
 * Sumber utama: database + RbacSeeder.
 */
return [
    'all' => [
        'manage_all',
        'manage_profil_sekolah',
        'manage_tahun_ajaran',
        'manage_users',
        'manage_murid',
        'manage_guru',
        'manage_kelas',
        'manage_mapel',
        'manage_ppdb',
        'manage_pengumuman',
        'view_dashboard_kepsek',
        'view_dashboard_guru',
        'view_dashboard_siswa',
        'view_dashboard_calon_siswa',
        'manage_profil_pribadi',
        'manage_pengaturan_akun',
        'view_pengumuman',
        'view_data_guru',
        'view_data_siswa',
        'view_data_kelas',
        'view_mapel',
        'view_data_ppdb',
        'view_transkrip_murid',
        'view_murid_diajar',
        'view_kelas_diajar',
        'view_mapel_diampu',
        'manage_absensi_siswa',
        'manage_nilai_siswa',
        'view_kelas_pribadi',
        'view_transkrip_pribadi',
        'view_absensi_pribadi',
        'view_nilai_pribadi',
        'manage_pendaftaran_pribadi',
        'manage_formulir_pendaftaran',
        'manage_berkas_pendaftaran',
        'submit_pendaftaran',
        'view_status_pendaftaran',
    ],

    'role_permissions' => [
        'admin' => ['manage_all'],
        'kepsek' => [
            'view_dashboard_kepsek',
            'manage_profil_pribadi',
            'manage_pengaturan_akun',
            'view_pengumuman',
            'view_data_guru',
            'view_data_siswa',
            'view_data_kelas',
            'view_mapel',
            'view_data_ppdb',
            'view_transkrip_murid',
        ],
        'guru' => [
            'view_dashboard_guru',
            'manage_profil_pribadi',
            'manage_pengaturan_akun',
            'view_pengumuman',
            'view_murid_diajar',
            'view_kelas_diajar',
            'view_mapel_diampu',
            'manage_absensi_siswa',
            'manage_nilai_siswa',
        ],
        'siswa' => [
            'view_dashboard_siswa',
            'manage_profil_pribadi',
            'manage_pengaturan_akun',
            'view_pengumuman',
            'view_kelas_pribadi',
            'view_mapel',
            'view_transkrip_pribadi',
            'view_nilai_pribadi',
        ],
        'calon_siswa' => [
            'view_dashboard_calon_siswa',
            'manage_pengaturan_akun',
            'manage_pendaftaran_pribadi',
            'manage_formulir_pendaftaran',
            'manage_berkas_pendaftaran',
            'submit_pendaftaran',
            'view_status_pendaftaran',
        ],
    ],

    'admin_inherits_all' => true,

    'redirect_paths' => [
        'admin' => '/admin/dashboard',
        'kepsek' => '/kepala-sekolah/dashboard',
        'guru' => '/guru/dashboard',
        'siswa' => '/siswa/dashboard',
        'calon_siswa' => '/calon-murid/dashboard',
    ],
];
