export const ROUTE_PERMISSIONS = {
  '/admin/dashboard': 'manage_all',
  '/admin/profil-sekolah': 'manage_profil_sekolah',
  '/admin/tahun-ajaran': 'manage_tahun_ajaran',
  '/admin/pengumuman': 'manage_pengumuman',
  '/admin/murid': 'manage_murid',
  '/admin/guru': 'manage_guru',
  '/admin/kelas': 'manage_kelas',
  '/admin/mapel': 'manage_mapel',
  '/admin/transkrip-akademik': 'view_transkrip_murid',
  '/admin/ppdb': 'manage_ppdb',
  '/admin/hak-akses': 'manage_users',
  '/admin/pengaturan': 'manage_pengaturan_akun',

  '/kepala-sekolah/dashboard': 'view_dashboard_kepsek',
  '/kepala-sekolah/profil-saya': 'manage_profil_pribadi',
  '/kepala-sekolah/profil-sekolah': 'view_dashboard_kepsek',
  '/kepala-sekolah/pengumuman': 'view_pengumuman',
  '/kepala-sekolah/data-guru': 'view_data_guru',
  '/kepala-sekolah/data-murid': 'view_data_siswa',
  '/kepala-sekolah/data-kelas': 'view_data_kelas',
  '/kepala-sekolah/data-mapel': 'view_mapel',
  '/kepala-sekolah/transkrip-akademik': 'view_transkrip_murid',
  '/kepala-sekolah/data-ppdb': 'view_data_ppdb',
  '/kepala-sekolah/pengaturan': 'manage_pengaturan_akun',

  '/kepsek/dashboard': 'view_dashboard_kepsek',
  '/kepsek/data': 'view_data_siswa',
  '/kepsek/ppdb': 'view_data_ppdb',

  '/guru/dashboard': 'view_dashboard_guru',
  '/guru/profil-saya': 'manage_profil_pribadi',
  '/guru/pengumuman': 'view_pengumuman',
  '/guru/murid': 'view_murid_diajar',
  '/guru/kelas': 'view_kelas_diajar',
  '/guru/mapel': 'view_mapel_diampu',
  '/guru/absensi': 'manage_absensi_siswa',
  '/guru/nilai': 'manage_nilai_siswa',
  '/guru/pengaturan': 'manage_pengaturan_akun',

  '/siswa/dashboard': 'view_dashboard_siswa',
  '/siswa/profil-saya': 'manage_profil_pribadi',
  '/siswa/pengumuman': 'view_pengumuman',
  '/siswa/kelas': 'view_kelas_pribadi',
  '/siswa/mapel': 'view_mapel',
  '/siswa/nilai': 'view_transkrip_pribadi',
  '/siswa/absensi': 'view_absensi_pribadi',
  '/siswa/pengaturan': 'manage_pengaturan_akun',

  '/calon-murid/dashboard': 'view_dashboard_calon_siswa',
  '/ppdb/dashboard': 'view_dashboard_calon_siswa',
  '/calon-siswa/dashboard': 'view_dashboard_calon_siswa',
  '/ppdb/registrasi': 'manage_formulir_pendaftaran',
  '/calon-murid/formulir': 'manage_formulir_pendaftaran',
  '/calon-murid/berkas': 'manage_berkas_pendaftaran',
  '/calon-murid/upload-berkas': 'manage_berkas_pendaftaran',
  '/calon-murid/status': 'view_status_pendaftaran',
  '/calon-murid/bukti': 'view_status_pendaftaran',
  '/calon-murid/pengaturan': 'manage_pengaturan_akun',
};

export function getPermissionForPath(path) {
  return ROUTE_PERMISSIONS[path] ?? null;
}
